# Generated by Django 3.1.4 on 2021-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0002_auto_20210321_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
