# Generated by Django 3.1.4 on 2021-03-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0003_auto_20210321_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
