# Generated by Django 3.1.4 on 2021-03-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0006_auto_20210324_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
