# Generated by Django 3.1.4 on 2021-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0009_auto_20210324_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
