# Generated by Django 3.1.4 on 2021-03-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0010_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencies.system'),
        ),
    ]
