# Generated by Django 3.1.4 on 2021-03-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0012_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='role',
            field=models.ManyToManyField(to='competencies.Role'),
        ),
    ]
