# Generated by Django 3.1.4 on 2021-03-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0016_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requirement',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='competencies.requirement'),
        ),
    ]
