# Generated by Django 3.1.4 on 2021-03-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0018_auto_20210325_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
