# Generated by Django 3.1.4 on 2021-03-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('competencies', '0020_auto_20210326_0627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
