# Generated by Django 3.1.4 on 2021-03-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0022_auto_20210326_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='upvote',
            field=models.BooleanField(null=True),
        ),
    ]
