# Generated by Django 3.1.4 on 2021-03-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('competencies', '0023_auto_20210331_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.ManyToManyField(related_name='tasks', to='auth.Group'),
        ),
    ]
