# Generated by Django 3.1.4 on 2021-03-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0024_auto_20210331_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
    ]
