# Generated by Django 3.1.4 on 2021-04-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0025_auto_20210331_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='imgFileName',
            field=models.CharField(blank=True, default='icon.png', max_length=300, null=True),
        ),
    ]
