# Generated by Django 3.1.4 on 2021-04-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0026_system_imgfilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='imgFileName',
            field=models.CharField(blank=True, default='Dwight_School_Logo.png', max_length=300, null=True),
        ),
    ]
