# Generated by Django 3.1.4 on 2021-04-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0028_csvupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
