# Generated by Django 3.1.4 on 2021-04-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0030_auto_20210405_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencies.system'),
        ),
    ]
