# Generated by Django 3.1.4 on 2021-04-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0031_auto_20210405_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
