# Generated by Django 3.1.4 on 2021-05-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0032_task_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users_completed',
            field=models.IntegerField(default=0),
        ),
    ]
