# Generated by Django 3.1.4 on 2021-05-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0033_task_users_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='users_completed',
            new_name='usersCompleted',
        ),
    ]
