# Generated by Django 3.1.4 on 2021-11-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0035_auto_20210519_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='imgFileName',
            field=models.CharField(blank=True, default='dwightschoolIcon.png', max_length=300, null=True),
        ),
    ]
