# Generated by Django 3.1.4 on 2021-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0035_auto_20210519_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='systemLogo',
            field=models.FileField(null=True, upload_to='static/'),
        ),
    ]
