# Generated by Django 3.0.5 on 2020-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='desc',
            field=models.CharField(default='', max_length=400),
        ),
    ]
