# Generated by Django 3.0.5 on 2020-12-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_list_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[('1', 'High priority'), ('2', 'Medium priority'), ('3', 'Low priority')], default='', max_length=1),
        ),
    ]
