# Generated by Django 3.1.4 on 2021-01-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20210111_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='dueDate',
            new_name='arrivalDate',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='priority',
            new_name='yearLevel',
        ),
        migrations.AddField(
            model_name='list',
            name='leavingDate',
            field=models.DateField(null=True),
        ),
    ]
