# Generated by Django 3.1.4 on 2021-01-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20210112_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocol',
            old_name='type',
            new_name='protocolType',
        ),
        migrations.RenameField(
            model_name='protocol_type',
            old_name='name',
            new_name='protocolTypeName',
        ),
        migrations.RenameField(
            model_name='responsibility',
            old_name='person',
            new_name='personResponsible',
        ),
        migrations.RenameField(
            model_name='responsibility',
            old_name='task',
            new_name='taskResponsible',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='TaskDescription',
        ),
        migrations.RenameField(
            model_name='task_data',
            old_name='protocol',
            new_name='protocolLink',
        ),
    ]
