# Generated by Django 3.1.4 on 2021-01-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_auto_20210112_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='protocol_type',
            new_name='protocolType',
        ),
        migrations.RenameModel(
            old_name='task_Data',
            new_name='taskData',
        ),
    ]
