# Generated by Django 3.1.4 on 2021-03-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(default=None, max_length=50, null=True)),
                ('surname', models.CharField(default=None, max_length=50, null=True)),
                ('yearLevel', models.CharField(choices=[('K1', 'K1'), ('K2', 'K2'), ('R', 'R'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5'), ('D1', 'D1'), ('D2', 'D2')], default=None, max_length=2)),
                ('completed', models.BooleanField(default=False, null=True)),
                ('arrivalDate', models.DateField(blank=True, null=True)),
                ('leavingDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(default='field', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('email', models.CharField(default=None, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='protocoltype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolTypeName', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('protocolFields', models.ManyToManyField(to='todo_list.ListFields')),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskDescription', models.CharField(default='', max_length=250)),
                ('person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='todo_list.persons')),
                ('protocolType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo_list.protocoltype')),
            ],
        ),
        migrations.CreateModel(
            name='protocol',
            fields=[
                ('list_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo_list.list')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo_list.protocoltype')),
            ],
            bases=('todo_list.list', models.Model),
        ),
        migrations.CreateModel(
            name='taskdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completionDate', models.DateField(null=True)),
                ('notes', models.CharField(default='', max_length=250)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.task')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.protocol')),
            ],
        ),
    ]
