# Generated by Django 3.0.5 on 2020-04-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='dateDeadline',
            field=models.DateTimeField(null=True),
        ),
    ]
