# Generated by Django 3.1.4 on 2021-01-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocoltype',
            name='fields',
        ),
        migrations.AddField(
            model_name='protocoltype',
            name='fields',
            field=models.ManyToManyField(blank=True, to='todo_list.List'),
        ),
    ]
