# Generated by Django 3.1.4 on 2021-02-16 13:31

from django.db import migrations, models
import django.forms.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='arrivalDate',
            field=models.DateField(blank=True, default=django.forms.fields.DateTimeField),
        ),
        migrations.AlterField(
            model_name='list',
            name='leavingDate',
            field=models.DateField(blank=True, default=django.forms.fields.DateTimeField),
        ),
        migrations.AlterField(
            model_name='list',
            name='yearLevel',
            field=models.CharField(choices=[('1', 'yr 1'), ('2', 'yr 2'), ('3', 'yr 3')], default=None, max_length=1),
        ),
    ]
