# Generated by Django 3.1.4 on 2021-01-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20210127_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocoltype',
            name='fields',
        ),
    ]
