# Generated by Django 3.0.5 on 2020-04-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_list_datedeadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='dateDeadline',
        ),
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.CharField(default='', max_length=50),
        ),
    ]
