# Generated by Django 3.1.4 on 2021-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20210219_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoltype',
            name='protocolTypeName',
            field=models.CharField(default='All protocols', max_length=100),
        ),
    ]
