# Generated by Django 3.1.4 on 2021-01-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_remove_protocoltype_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.BooleanField(default=False, null=True)),
                ('surname', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='protocoltype',
            name='fields',
            field=models.ManyToManyField(to='todo_list.ListFields'),
        ),
    ]
