# Generated by Django 3.1.4 on 2021-05-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20210512_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='yearLevel',
            field=models.CharField(blank=True, choices=[('N1', 'N1'), ('N2', 'N2'), ('R', 'R'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5'), ('D1', 'D1'), ('D2', 'D2')], default=None, max_length=2, null=True),
        ),
    ]
