# Generated by Django 3.1.4 on 2021-02-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20210221_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoltype',
            name='protocolTypeName',
            field=models.CharField(max_length=100),
        ),
    ]
