# Generated by Django 3.1.4 on 2021-01-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20201204_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='list',
            name='item',
        ),
        migrations.AddField(
            model_name='list',
            name='forename',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='list',
            name='surname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[('1', 'yr 1'), ('2', 'yr 2'), ('3', 'yr 3')], default='', max_length=1),
        ),
    ]
