# Generated by Django 3.1.4 on 2021-01-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_auto_20210127_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfields',
            name='field',
            field=models.CharField(default='field', max_length=50),
        ),
    ]
