# Generated by Django 3.1.4 on 2021-01-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_auto_20210111_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo_list.list')),
            ],
        ),
        migrations.CreateModel(
            name='protocol_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=250)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=250)),
                ('protocolType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo_list.protocol_type')),
            ],
        ),
        migrations.CreateModel(
            name='task_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completionDate', models.DateField(null=True)),
                ('notes', models.CharField(default='', max_length=250)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.protocol')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.task')),
            ],
        ),
        migrations.CreateModel(
            name='responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.persons')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.task')),
            ],
        ),
        migrations.CreateModel(
            name='protocol_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.list')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.protocol_type')),
            ],
        ),
        migrations.AddField(
            model_name='protocol',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo_list.protocol_type'),
        ),
    ]
