# Generated by Django 3.1.4 on 2021-02-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_auto_20210127_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo_list.protocoltype'),
        ),
    ]
