# Generated by Django 3.1.4 on 2021-01-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_auto_20210112_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol_type',
            name='fields',
            field=models.CharField(choices=[('forename', 'First name'), ('surname', 'Second name'), ('yearLevel', 'year level')], default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='protocol_field',
        ),
    ]
