# Generated by Django 3.1.4 on 2021-01-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_auto_20210112_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='protocoltype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('fields', models.CharField(choices=[('forename', 'First name'), ('surname', 'Second name'), ('yearLevel', 'year level'), ('arrivalDate', 'when joining roll'), ('leavingDate', 'when leaving roll')], default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='protocol',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo_list.protocoltype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='protocolType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo_list.protocoltype'),
        ),
        migrations.DeleteModel(
            name='protocol_type',
        ),
    ]
