# Generated by Django 3.1.4 on 2021-01-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0009_auto_20210118_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocoltype',
            old_name='name',
            new_name='protocolTypeName',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='TaskDescription',
        ),
    ]
