# Generated by Django 3.1.4 on 2021-01-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0010_auto_20210118_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task_Data',
            new_name='taskdata',
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todo_list.persons'),
        ),
    ]
